default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snippetbox_development
  username: snippetbox
  password: snippetbox
  host: db
  port: 5432

test:
  <<: *default
  database: snippetbox_test
  username: snippetbox
  password: snippetbox
  host: db
  port: 5432

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>